### ISSUE TITLE
DOC: Visual description of each symbol

### ISSUE THREAD

**Issue by westurner** [Code-and-Response/DroneAid#23]
A written description of each symbol in the README table could be helpful for training and memory purposes.

I wrote this; please feel free to reuse none or any of it without attribution:

> Each of the symbols are drawn within a triangle pointing up:
> - Immediate Help Needed (orange; downward triangle \n SOS),
> - Shelter Needed (cyan; like a guy standing in a tall pentagon without a floor),
> - OK: No Help Needed (green; upward triangle \n OK),
> - First Aid Kit Needed (yellow; briefcase with a first aid cross),
> - Water Needed (blue; rain droplet),
> - Area with Children in Need (lilac; baby looking thing with a diaper on),
> - Food Needed (red; pan with wheat drawn above it),
> - Area with Elderly in Need (purple; person with a cane)

**Comment by krook** [comment]
Thanks for the contribution @westurner! I've updated the README and listed you as a contributor.

**Comment by westurner** [comment]
Thanks!
