### ISSUE TITLE
Address the security alert

### ISSUE THREAD

**Issue by krook** [Code-and-Response/DroneAid#25]
**Describe the bug**
One of the NPM packages has a security issue. Committers can see it.

@pedrocruzio @vabarbosa @bourdakos1 @johnwalicki can you try to upgrade and test?

**Comment by johnwalicki** [comment]
I can't see the security issue details.

**Comment by krook** [comment]
@johnwalicki I upgraded the default team access to Maintain. Do you see it now?

**Comment by krook** [comment]
Thanks @vabarbosa!
